#!/usr/bin/env python3
"""Harness surfaces — one canonical brief, one skills tree, one MCP file.

This project keeps a single source of truth:

    AGENTS.md          the brief every AI tool reads
    .claude/skills/    the seat playbooks
    .mcp.json          the MCP connectors

Every other harness's surface is *derived* from those — a pointer, a symlink, or
a generated block — so the copies cannot drift. This script regenerates them and,
with --check, fails when they have drifted. It is the same rule `CLAUDE.md`
already lives under, applied to Codex, Copilot and the rest.

Usage:
  scripts/harness/sync.py --check      # exit 1 if a derived surface is stale
  scripts/harness/sync.py --write      # regenerate them
  scripts/harness/sync.py --list       # show detected harnesses

Adapters are data (harnesses.json); this file only interprets them. Stdlib only.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import merge  # noqa: E402

TABLE_REL = "harnesses.json"

POINTER_MD = """\
# {label} — pointer

**This file carries no rules of its own. The single source of truth is
[`AGENTS.md`](./AGENTS.md) — read it first.**

Mission, hard constraints, trust tiers, MCP posture, roles and seats, the
knowledge-grounding rule and the deliverable rules all live in `AGENTS.md`.
It is the brief every AI tool reads, which is exactly why it is the one place
we maintain.

A diff that changes this file without changing `AGENTS.md` is a mistake.
If the two ever disagree, `AGENTS.md` wins.
"""

POINTER_MDC = """\
---
description: {label} rules — pointer to the canonical brief
alwaysApply: true
---

This file carries no rules of its own. The single source of truth is
`AGENTS.md` at the repo root — read it first.

If this file and `AGENTS.md` ever disagree, `AGENTS.md` wins.
"""


def load_table(path=None) -> dict:
    path = Path(path) if path else Path(__file__).with_name(TABLE_REL)
    table = json.loads(path.read_text(encoding="utf-8"))
    return {k: v for k, v in table.items() if not k.startswith("$")}


def probe(root, spec: str) -> bool:
    kind, _, value = spec.partition(":")
    if kind == "cmd":
        return shutil.which(value) is not None
    if kind == "path":
        return (Path(root) / value).exists()
    return False


def detect(root, table: dict) -> list[str]:
    """Harnesses whose CLI is installed or whose config already lives in the repo."""
    return [name for name, spec in table.items()
            if any(probe(root, p) for p in spec.get("detect", []))]


def pointer_text(spec: dict) -> str:
    template = POINTER_MDC if spec.get("style") == "mdc" else POINTER_MD
    return template.format(label=spec.get("label", "This tool"))


# --- Copilot surfaces ------------------------------------------------------

GENERATED_MARK = "Generated by scripts/harness/sync.py"
REGENERATE = "python3 scripts/harness/sync.py --write"

COPILOT_BRIEF = """\
<!-- {mark} from AGENTS.md — do not edit. Regenerate: {regen} -->
# GitHub Copilot — project brief

**The single source of truth is [`AGENTS.md`](../AGENTS.md). Read it in full before any project work.**
IntelliJ's Copilot Chat does not load `AGENTS.md` by itself, so the sections every
session needs are copied below verbatim. If this file and `AGENTS.md` ever disagree,
`AGENTS.md` wins.

**No session hook ran?** (IntelliJ has none.) Run `bash scripts/session/start.sh`
yourself at the start of the session and follow its output.

{sections}
"""

_SECTION = re.compile(r"^## (\d+)\.", re.M)


def agents_sections(text: str, numbers) -> str:
    """The `## N.` sections of AGENTS.md named in `numbers`, verbatim, in file order."""
    starts = [(m.group(1), m.start()) for m in _SECTION.finditer(text)]
    found = {num for num, _ in starts}
    missing = [n for n in numbers if n not in found]
    if missing:
        raise ValueError(f"AGENTS.md has no section(s): {', '.join(missing)}")
    chunks = []
    for i, (num, pos) in enumerate(starts):
        if num in numbers:
            end = starts[i + 1][1] if i + 1 < len(starts) else len(text)
            chunk = text[pos:end].rstrip()
            if chunk.endswith("---"):
                chunk = chunk[:-3].rstrip()
            chunks.append(chunk)
    return "\n\n".join(chunks)


def render_copilot_brief(root, spec: dict) -> str:
    agents = (Path(root) / "AGENTS.md").read_text(encoding="utf-8")
    body = agents_sections(agents, spec.get("sections", ["0", "3"]))
    body = body.replace("](./", "](../")   # the brief lives in .github/
    return COPILOT_BRIEF.format(mark=GENERATED_MARK, regen=REGENERATE, sections=body)


def _split_frontmatter(text: str) -> tuple[str, str]:
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end != -1:
            return text[4:end], text[end + 4:].lstrip("\n")
    return "", text


def _rule_paths(front: str) -> list[str]:
    """The `paths:` list of a .claude/rules frontmatter (the only key the rules use)."""
    out, inside = [], False
    for line in front.splitlines():
        if re.match(r"^paths:\s*$", line):
            inside = True
            continue
        if inside:
            m = re.match(r"""^\s+-\s+["']?([^"']+?)["']?\s*$""", line)
            if m:
                out.append(m.group(1))
                continue
            if line.strip():
                inside = False
    return out


def render_copilot_instructions(root, spec: dict) -> dict:
    """{repo-relative path: text} — one .instructions.md per .claude/rules/*.md."""
    src_rel = spec.get("from", ".claude/rules")
    src = Path(root) / src_rel
    files = {}
    for rule in sorted(src.glob("*.md")) if src.is_dir() else []:
        front, body = _split_frontmatter(rule.read_text(encoding="utf-8"))
        apply_to = ",".join(_rule_paths(front)) or "**"
        rel = f"{spec['path']}/{rule.stem}.instructions.md"
        files[rel] = (f"---\napplyTo: '{apply_to}'\n---\n"
                      f"<!-- {GENERATED_MARK} from {src_rel}/{rule.name} — do not edit. "
                      f"Regenerate: {REGENERATE} -->\n\n{body}")
    return files


def orphan_instructions(root, spec: dict, wanted: dict) -> list[str]:
    """Generated instruction files whose source rule was deleted. Never touches files we did not write."""
    out_dir = Path(root) / spec["path"]
    if not out_dir.is_dir():
        return []
    orphans = []
    for p in sorted(out_dir.glob("*.instructions.md")):
        rel = f"{spec['path']}/{p.name}"
        if rel not in wanted and GENERATED_MARK in p.read_text(encoding="utf-8"):
            orphans.append(rel)
    return orphans


VSCODE_HOOKS_KEY = "chat.useClaudeHooks"


def render_vscode_settings(existing_text: str) -> str:
    """Union the kit's one key into .vscode/settings.json. Operator values win.

    VS Code settings are often JSONC (comments). We never rewrite a file we cannot
    parse; `check` reports it and the operator sets the key by hand.
    """
    try:
        text, _ = merge.merge_json(existing_text, json.dumps({VSCODE_HOOKS_KEY: True}))
    except ValueError:
        return existing_text
    return text


def vscode_hooks_state(text: str) -> str:
    try:
        data = json.loads(text) if text.strip() else {}
    except json.JSONDecodeError:
        return "unparseable"
    if VSCODE_HOOKS_KEY not in data:
        return "missing"
    return "ok" if data[VSCODE_HOOKS_KEY] is True else "disabled"


def _git_ignored(root, rel) -> bool:
    """True only when git says `rel` is ignored in this repo. No git, or no repo: False."""
    try:
        r = subprocess.run(["git", "check-ignore", "-q", rel], cwd=root,
                           capture_output=True, timeout=10, check=False)
    except (OSError, subprocess.SubprocessError):
        return False
    return r.returncode == 0


COPILOT_FORMATS = ("copilot-brief", "copilot-instructions", "vscode-claude-hooks")


def materialize(root, sspec: dict) -> list[tuple[str, str, str]]:
    """(rel, text, install-class) for a generated Copilot surface. Shared by sync and the installer."""
    fmt = sspec.get("format")
    if fmt == "copilot-brief":
        return [(sspec["path"], render_copilot_brief(root, sspec), "own")]
    if fmt == "copilot-instructions":
        return [(rel, text, "own")
                for rel, text in render_copilot_instructions(root, sspec).items()]
    if fmt == "vscode-claude-hooks":
        path = Path(root) / sspec["path"]
        have = path.read_text(encoding="utf-8") if path.is_file() else ""
        return [(sspec["path"], render_vscode_settings(have), "merge")]
    return []


def _instruction_specs(table, harnesses):
    """The generated copilot-instructions spec of each harness, found even when no rules exist."""
    for name in harnesses:
        rspec = (table.get(name) or {}).get("rules") or {}
        if rspec.get("kind") == "generated" and rspec.get("format") == "copilot-instructions":
            yield rspec


# --- MCP translation -------------------------------------------------------

PLACEHOLDER = re.compile(r"<[A-Z][A-Z_/]{2,}>")


def unconfigured(cfg: dict) -> bool:
    """True when a server entry still carries an unfilled <PLACEHOLDER>.

    Emitting one into a harness config makes that harness dial a bogus endpoint
    on every session, so placeholder servers are skipped until someone fills
    them in. `doctor` reports what was skipped.
    """
    return bool(PLACEHOLDER.search(json.dumps(cfg)))


def mcp_servers(mcp: dict, skipped: list | None = None) -> dict:
    """Ready-to-run servers in a .mcp.json.

    Drops $comment/$note documentation keys, `$disabled` entries, and any server
    still holding a placeholder. Names of the last two land in `skipped`.
    """
    servers = mcp.get("mcpServers") or {}
    out = {}
    for name, cfg in servers.items():
        if name.startswith("$") or not isinstance(cfg, dict):
            continue
        clean = {k: v for k, v in cfg.items() if not k.startswith("$")}
        if cfg.get("$disabled"):
            if skipped is not None:
                skipped.append(f"{name} (disabled)")
            continue
        if unconfigured(clean):
            if skipped is not None:
                skipped.append(f"{name} (unfilled placeholder)")
            continue
        out[name] = clean
    return out


def to_codex_toml(mcp: dict) -> str:
    """Render .mcp.json servers as Codex `[mcp_servers.<name>]` tables."""
    lines = ["# Generated from .mcp.json by scripts/install — do not edit by hand.",
             "# Regenerate:  ./install.sh --into . --sync"]
    for name, cfg in sorted(mcp_servers(mcp).items()):
        lines.append("")
        lines.append(f"[mcp_servers.{merge.toml_key(name)}]")
        for key in ("command", "url"):
            if key in cfg:
                lines.append(f"{key} = {merge.toml_value(cfg[key])}")
        if cfg.get("args"):
            lines.append(f"args = {merge.toml_value(list(cfg['args']))}")
        env = cfg.get("env")
        if isinstance(env, dict) and env:
            lines.append("")
            lines.append(f"[mcp_servers.{merge.toml_key(name)}.env]")
            for k, v in sorted(env.items()):
                lines.append(f"{merge.toml_key(k)} = {merge.toml_value(v)}")
    return "\n".join(lines)


def to_copilot_mcp(mcp: dict) -> dict:
    """Render .mcp.json servers in Copilot CLI's mcp-config.json schema.

    Local: {command, args, tools, [cwd, env, timeout], type: "local"}
    Remote: {url, tools, type: "http"|"sse", [headers, timeout]}
    `tools` is required by Copilot's schema; "*" enables the server's full set.
    """
    out = {}
    for name, cfg in sorted(mcp_servers(mcp).items()):
        if "url" in cfg:
            entry = {"type": "sse" if cfg.get("type") == "sse" else "http",
                     "url": cfg["url"], "tools": ["*"]}
            if isinstance(cfg.get("headers"), dict):
                entry["headers"] = cfg["headers"]
        elif "command" in cfg:
            entry = {"type": "local", "command": cfg["command"],
                     "args": list(cfg.get("args") or []), "tools": ["*"]}
            if isinstance(cfg.get("env"), dict) and cfg["env"]:
                entry["env"] = cfg["env"]
            if cfg.get("cwd"):
                entry["cwd"] = cfg["cwd"]
        else:
            continue
        out[name] = entry
    return {"mcpServers": out}


# --- hook translation ------------------------------------------------------

def to_codex_hooks(settings: dict) -> dict:
    """Codex's hooks file uses Claude Code's event names and matcher/hooks shape.

    Events Codex understands: PreToolUse, PostToolUse, PermissionRequest,
    PreCompact, PostCompact, SessionStart, UserPromptSubmit, SubagentStart,
    SubagentStop, Stop. SessionEnd is Claude-only and is dropped.
    """
    known = {"PreToolUse", "PostToolUse", "PermissionRequest", "PreCompact",
             "PostCompact", "SessionStart", "UserPromptSubmit", "SubagentStart",
             "SubagentStop", "Stop"}
    events = {}
    for event, groups in (settings.get("hooks") or {}).items():
        if event not in known:
            continue
        cleaned = []
        for group in groups:
            group = {k: v for k, v in group.items() if not k.startswith("_")}
            if group.get("hooks"):
                cleaned.append(group)
        if cleaned:
            events[event] = cleaned
    return {"hooks": events}


# --- drift check -----------------------------------------------------------

SURFACES = ("brief", "rules", "mcp", "hooks")


def derived_surfaces(root, table, harnesses):
    """(rel, want_text, mode, spec) for every generated surface of the given harnesses.

    mode: 'whole-file' | 'block' (TOML block) | 'json-key' (VS Code switch)
    """
    root = Path(root)
    mcp_path = root / ".mcp.json"
    mcp = json.loads(mcp_path.read_text(encoding="utf-8")) if mcp_path.is_file() else {}

    for name in harnesses:
        spec = table.get(name) or {}
        for surface in SURFACES:
            sspec = spec.get(surface) or {}
            if sspec.get("kind") != "generated":
                continue
            fmt = sspec.get("format")
            if fmt in COPILOT_FORMATS:
                mode = "json-key" if fmt == "vscode-claude-hooks" else "whole-file"
                for rel, text, _cls in materialize(root, sspec):
                    yield rel, text, mode, sspec
            elif surface == "mcp" and fmt == "copilot-mcp":
                yield sspec["path"], json.dumps(to_copilot_mcp(mcp), indent=2) + "\n", "whole-file", sspec
            elif surface == "mcp" and fmt == "toml-block":
                yield sspec["path"], to_codex_toml(mcp), "block", sspec


def check(root, table, harnesses) -> list[str]:
    root = Path(root)
    deferred = _deferred(root)
    problems = []
    for rel, want, mode, sspec in derived_surfaces(root, table, harnesses):
        path = root / rel
        if mode == "json-key":
            if _git_ignored(root, rel):
                continue  # kept out of git on purpose: no clone has it, so nothing to gate
            state = vscode_hooks_state(path.read_text(encoding="utf-8") if path.is_file() else "")
            if state == "missing":
                problems.append(f'{rel} lacks "{VSCODE_HOOKS_KEY}": true')
            elif state == "unparseable":
                problems.append(f'{rel} is JSONC — set "{VSCODE_HOOKS_KEY}": true by hand')
            continue  # 'disabled' is an operator choice, not drift
        if not path.is_file():
            problems.append(f"{rel} is missing")
            continue
        have = path.read_text(encoding="utf-8")
        if mode == "whole-file" and have != want:
            problems.append(_kept(rel) if rel in deferred else f"{rel} differs from its source")
        elif mode == "block":
            block = merge.extract_block(have)
            if block is None or want.strip() not in block:
                problems.append(f"{rel} block differs from .mcp.json")
    for rspec in _instruction_specs(table, harnesses):
        wanted = set(render_copilot_instructions(root, rspec))
        for orphan in orphan_instructions(root, rspec, wanted):
            problems.append(f"{orphan} is an orphan")
    return problems


def write(root, table, harnesses, errors: list | None = None) -> list[str]:
    root = Path(root)
    deferred = _deferred(root)
    written = []
    for rel, want, mode, sspec in derived_surfaces(root, table, harnesses):
        path = root / rel
        if rel in deferred and path.is_file() and path.read_text(encoding="utf-8") != want:
            if errors is not None:
                errors.append(_kept(rel))         # never overwrite a file you kept
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        have = path.read_text(encoding="utf-8") if path.is_file() else ""
        out = merge.merge_toml_block(have, want) if mode == "block" else want
        if out != have:
            path.write_text(out, encoding="utf-8")
            written.append(rel)
    for rspec in _instruction_specs(table, harnesses):
        wanted = set(render_copilot_instructions(root, rspec))
        for orphan in orphan_instructions(root, rspec, wanted):
            (root / orphan).unlink()
            written.append(f"{orphan} (removed)")
    return written


def installed_harnesses(root) -> list[str]:
    """Harnesses this repo was wired for, per the install manifest."""
    man = Path(root) / ".ai-sdlc/manifest.json"
    if man.is_file():
        try:
            return json.loads(man.read_text(encoding="utf-8")).get("harnesses", [])
        except json.JSONDecodeError:
            pass
    return []


def _deferred(root) -> dict:
    """Generated files the operator kept at install time (manifest `deferred`)."""
    man = Path(root) / ".ai-sdlc/manifest.json"
    try:
        data = json.loads(man.read_text(encoding="utf-8")) if man.is_file() else {}
    except (json.JSONDecodeError, OSError):
        return {}
    return (data.get("deferred") or {}) if isinstance(data, dict) else {}


def _kept(rel) -> str:
    return (f"{rel} is your file (kit copy in {rel}.kit-new) — merge it into its source, "
            f"delete it, then run {REGENERATE}")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args(argv)

    root = Path(args.root).resolve()
    table = load_table()
    harnesses = installed_harnesses(root) or detect(root, table)

    if args.list:
        for name in harnesses:
            print(f"{name}\t{table.get(name, {}).get('label', name)}")
        return 0

    if args.write:
        errors = []
        for rel in write(root, table, harnesses, errors):
            print(f"regenerated {rel}")
        for line in errors:
            print(f"not regenerated: {line}", file=sys.stderr)
        return 1 if errors else 0

    problems = check(root, table, harnesses)
    for line in problems:
        print(f"drift: {line}", file=sys.stderr)
    if problems:
        print(f"\nRegenerate with: {REGENERATE}", file=sys.stderr)
        return 1
    print(f"harness surfaces match their sources ({len(harnesses)} harness(es))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
