#!/usr/bin/env python3
"""Unit tests for the Copilot surfaces generated by scripts/harness/sync.py."""
import json
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "harness"))
import sync  # noqa: E402

AGENTS = """# AGENTS.md — `Demo`

Intro.

---

## 0. Startup — user identity and onboarding

1. **If `USER.md` does not exist** → follow [`ONBOARDING.md`](./ONBOARDING.md).

---

## 1. Mission

Not copied.

## 3. Hard constraints (non-negotiable)

- **No secrets in the repo.**

## 4. AI tools & the trust contract

### 4.1 Tools in use

Not copied either.
"""

BRIEF_SPEC = {"kind": "generated", "path": ".github/copilot-instructions.md",
              "format": "copilot-brief", "sections": ["0", "3"]}


def repo(tmp, agents=AGENTS):
    root = Path(tmp)
    (root / "AGENTS.md").write_text(agents, encoding="utf-8")
    return root


class TestBrief(unittest.TestCase):
    def test_inlines_only_the_requested_sections(self):
        with tempfile.TemporaryDirectory() as tmp:
            text = sync.render_copilot_brief(repo(tmp), BRIEF_SPEC)
            self.assertIn("## 0. Startup", text)
            self.assertIn("## 3. Hard constraints", text)
            self.assertNotIn("## 1. Mission", text)
            self.assertNotIn("### 4.1", text)

    def test_marks_itself_generated_and_points_at_agents(self):
        with tempfile.TemporaryDirectory() as tmp:
            text = sync.render_copilot_brief(repo(tmp), BRIEF_SPEC)
            self.assertIn(sync.GENERATED_MARK, text)
            self.assertIn("](../AGENTS.md)", text)

    def test_rewrites_repo_relative_links_for_the_github_folder(self):
        with tempfile.TemporaryDirectory() as tmp:
            text = sync.render_copilot_brief(repo(tmp), BRIEF_SPEC)
            self.assertIn("](../ONBOARDING.md)", text)
            self.assertNotIn("](./ONBOARDING.md)", text)

    def test_drops_section_separators(self):
        with tempfile.TemporaryDirectory() as tmp:
            text = sync.render_copilot_brief(repo(tmp), BRIEF_SPEC)
            self.assertNotIn("\n---\n\n## 3.", text)

    def test_missing_section_is_an_error_not_a_silent_gap(self):
        with tempfile.TemporaryDirectory() as tmp:
            spec = dict(BRIEF_SPEC, sections=["0", "9"])
            with self.assertRaises(ValueError) as ctx:
                sync.render_copilot_brief(repo(tmp), spec)
            self.assertIn("9", str(ctx.exception))


if __name__ == "__main__":
    unittest.main()
