#!/usr/bin/env python3
"""Unit tests for the Copilot surfaces generated by scripts/harness/sync.py."""
import contextlib
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "harness"))
import sync  # noqa: E402

AGENTS = """# AGENTS.md — `Demo`

Intro.

---

## 0. Startup — user identity and onboarding

1. **If `USER.md` does not exist** → follow [`ONBOARDING.md`](./ONBOARDING.md).

---

## 1. Mission

Not copied.

## 3. Hard constraints (non-negotiable)

- **No secrets in the repo.**

## 4. AI tools & the trust contract

### 4.1 Tools in use

Not copied either.
"""

BRIEF_SPEC = {"kind": "generated", "path": ".github/copilot-instructions.md",
              "format": "copilot-brief", "sections": ["0", "3"]}


def repo(tmp, agents=AGENTS):
    root = Path(tmp)
    (root / "AGENTS.md").write_text(agents, encoding="utf-8")
    return root


class TestBrief(unittest.TestCase):
    def test_inlines_only_the_requested_sections(self):
        with tempfile.TemporaryDirectory() as tmp:
            text = sync.render_copilot_brief(repo(tmp), BRIEF_SPEC)
            self.assertIn("## 0. Startup", text)
            self.assertIn("## 3. Hard constraints", text)
            self.assertNotIn("## 1. Mission", text)
            self.assertNotIn("### 4.1", text)

    def test_marks_itself_generated_and_points_at_agents(self):
        with tempfile.TemporaryDirectory() as tmp:
            text = sync.render_copilot_brief(repo(tmp), BRIEF_SPEC)
            self.assertIn(sync.GENERATED_MARK, text)
            self.assertIn("](../AGENTS.md)", text)

    def test_rewrites_repo_relative_links_for_the_github_folder(self):
        with tempfile.TemporaryDirectory() as tmp:
            text = sync.render_copilot_brief(repo(tmp), BRIEF_SPEC)
            self.assertIn("](../ONBOARDING.md)", text)
            self.assertNotIn("](./ONBOARDING.md)", text)

    def test_drops_section_separators(self):
        with tempfile.TemporaryDirectory() as tmp:
            text = sync.render_copilot_brief(repo(tmp), BRIEF_SPEC)
            self.assertNotIn("\n---\n\n## 3.", text)

    def test_missing_section_is_an_error_not_a_silent_gap(self):
        with tempfile.TemporaryDirectory() as tmp:
            spec = dict(BRIEF_SPEC, sections=["0", "9"])
            with self.assertRaises(ValueError) as ctx:
                sync.render_copilot_brief(repo(tmp), spec)
            self.assertIn("9", str(ctx.exception))


RULES_SPEC = {"kind": "generated", "path": ".github/instructions",
              "format": "copilot-instructions", "from": ".claude/rules"}


def rules(tmp, files):
    root = Path(tmp)
    (root / ".claude/rules").mkdir(parents=True)
    for name, text in files.items():
        (root / ".claude/rules" / name).write_text(text, encoding="utf-8")
    return root


def apply_to(front):
    """The applyTo line generated for a rule with this frontmatter."""
    with tempfile.TemporaryDirectory() as tmp:
        root = rules(tmp, {"r.md": f"---\n{front}---\n# R\n"})
        text = sync.render_copilot_instructions(root, RULES_SPEC)[
            ".github/instructions/r.instructions.md"]
        return text.splitlines()[1]


class TestInstructions(unittest.TestCase):
    def test_paths_become_apply_to(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = rules(tmp, {"adr.md": '---\npaths:\n  - "docs/adr/**"\n  - "docs/x/**"\n---\n# ADR\nBody.\n'})
            out = sync.render_copilot_instructions(root, RULES_SPEC)
            text = out[".github/instructions/adr.instructions.md"]
            self.assertTrue(text.startswith("---\napplyTo: 'docs/adr/**,docs/x/**'\n---\n"))
            self.assertIn("# ADR\nBody.", text)
            self.assertIn(sync.GENERATED_MARK, text)

    def test_rule_without_paths_applies_everywhere(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = rules(tmp, {"tokens.md": "# Token economy\nRule.\n"})
            text = sync.render_copilot_instructions(root, RULES_SPEC)[
                ".github/instructions/tokens.instructions.md"]
            self.assertTrue(text.startswith("---\napplyTo: '**'\n---\n"))

    def test_orphans_are_only_our_generated_files(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = rules(tmp, {"a.md": "# A\n"})
            out_dir = root / ".github/instructions"
            out_dir.mkdir(parents=True)
            (out_dir / "gone.instructions.md").write_text(
                f"---\napplyTo: '**'\n---\n<!-- {sync.GENERATED_MARK} from "
                ".claude/rules/gone.md — do not edit. -->\n", encoding="utf-8")
            (out_dir / "cartograph.instructions.md").write_text("not ours\n", encoding="utf-8")
            wanted = sync.render_copilot_instructions(root, RULES_SPEC)
            self.assertEqual(sync.orphan_instructions(root, RULES_SPEC, wanted),
                             [".github/instructions/gone.instructions.md"])

    def test_a_copied_generated_file_is_not_an_orphan(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = rules(tmp, {"a.md": "# A\n"})
            wanted = sync.render_copilot_instructions(root, RULES_SPEC)
            out_dir = root / ".github/instructions"
            out_dir.mkdir(parents=True)
            (out_dir / "mine.instructions.md").write_text(       # copied to start my own
                wanted[".github/instructions/a.instructions.md"], encoding="utf-8")
            self.assertEqual(sync.orphan_instructions(root, RULES_SPEC, wanted), [])

    def test_a_note_quoting_the_mark_is_not_an_orphan(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = rules(tmp, {"a.md": "# A\n"})
            out_dir = root / ".github/instructions"
            out_dir.mkdir(parents=True)
            (out_dir / "notes.instructions.md").write_text(
                "---\napplyTo: '**'\n---\n# Notes\nGenerated files start with "
                f"`<!-- {sync.GENERATED_MARK} from .claude/rules/notes.md — do not edit.`\n",
                encoding="utf-8")
            wanted = sync.render_copilot_instructions(root, RULES_SPEC)
            self.assertEqual(sync.orphan_instructions(root, RULES_SPEC, wanted), [])

    def test_paths_accepts_the_yaml_shapes_rules_use(self):
        cases = {
            'paths:\n- "a/**"\n- b/**\n': "applyTo: 'a/**,b/**'",            # unindented
            'paths: ["a/**", \'b/**\']\n': "applyTo: 'a/**,b/**'",           # flow list
            "paths: a/**\n": "applyTo: 'a/**'",                               # scalar
            '# scope\npaths:\n  # docs first\n  - "a/**"  # ADRs\n  - b/**\n':
                "applyTo: 'a/**,b/**'",                                       # comments
        }
        for front, want in cases.items():
            with self.subTest(front=front):
                self.assertEqual(apply_to(front), want)

    def test_empty_paths_is_an_error_naming_the_rule(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = rules(tmp, {"r.md": "---\npaths:\n---\n# R\n"})
            with self.assertRaises(ValueError) as ctx:
                sync.render_copilot_instructions(root, RULES_SPEC)
            self.assertIn(".claude/rules/r.md", str(ctx.exception))

    def test_brace_glob_with_a_comma_is_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = rules(tmp, {"r.md": '---\npaths:\n  - "src/**/*.{ts,tsx}"\n---\n# R\n'})
            with self.assertRaises(ValueError) as ctx:
                sync.render_copilot_instructions(root, RULES_SPEC)
            self.assertIn("expand brace globs into separate paths", str(ctx.exception))


class TestVscode(unittest.TestCase):
    def test_adds_the_switch_and_keeps_existing_settings(self):
        out = sync.render_vscode_settings('{"editor.tabSize": 2}')
        data = json.loads(out)
        self.assertIs(data["chat.useClaudeHooks"], True)
        self.assertEqual(data["editor.tabSize"], 2)

    def test_operator_false_wins(self):
        out = sync.render_vscode_settings('{"chat.useClaudeHooks": false}')
        self.assertIs(json.loads(out)["chat.useClaudeHooks"], False)

    def test_jsonc_is_left_untouched(self):
        jsonc = '{\n  // my comment\n  "a": 1\n}\n'
        self.assertEqual(sync.render_vscode_settings(jsonc), jsonc)

    def test_state(self):
        self.assertEqual(sync.vscode_hooks_state('{"chat.useClaudeHooks": true}'), "ok")
        self.assertEqual(sync.vscode_hooks_state('{}'), "missing")
        self.assertEqual(sync.vscode_hooks_state('{"chat.useClaudeHooks": false}'), "disabled")
        self.assertEqual(sync.vscode_hooks_state('{ // c\n}'), "unparseable")

    def test_non_object_settings_are_unparseable(self):
        for text in ("1", "[]", '"x"'):
            with self.subTest(text=text):
                self.assertEqual(sync.vscode_hooks_state(text), "unparseable")


class TestCheckWrite(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = repo(self.tmp.name)
        (self.root / ".claude/rules").mkdir(parents=True)
        (self.root / ".claude/rules/adr.md").write_text(
            '---\npaths:\n  - "docs/adr/**"\n---\n# ADR\n', encoding="utf-8")
        self.table = sync.load_table()

    def tearDown(self):
        self.tmp.cleanup()

    def test_fresh_repo_drifts_then_write_fixes_it(self):
        problems = sync.check(self.root, self.table, ["copilot-cli"])
        self.assertTrue(any("copilot-instructions.md" in p for p in problems))
        written = sync.write(self.root, self.table, ["copilot-cli"])
        self.assertIn(".github/copilot-instructions.md", written)
        self.assertIn(".github/instructions/adr.instructions.md", written)
        self.assertIn(".vscode/settings.json", written)
        self.assertEqual([p for p in sync.check(self.root, self.table, ["copilot-cli"])
                          if "mcp" not in p], [])

    def test_editing_agents_md_is_drift(self):
        sync.write(self.root, self.table, ["copilot-cli"])
        agents = self.root / "AGENTS.md"
        agents.write_text(agents.read_text().replace("No secrets", "No secrets, ever"),
                          encoding="utf-8")
        problems = sync.check(self.root, self.table, ["copilot-cli"])
        self.assertIn(".github/copilot-instructions.md differs from its source", problems)

    def test_deleted_rule_leaves_an_orphan_that_write_removes(self):
        sync.write(self.root, self.table, ["copilot-cli"])
        (self.root / ".claude/rules/adr.md").unlink()
        self.assertIn(".github/instructions/adr.instructions.md is an orphan",
                      sync.check(self.root, self.table, ["copilot-cli"]))
        sync.write(self.root, self.table, ["copilot-cli"])
        self.assertFalse((self.root / ".github/instructions/adr.instructions.md").exists())

    def test_unparseable_vscode_settings_is_reported_not_rewritten(self):
        vs = self.root / ".vscode/settings.json"
        vs.parent.mkdir()
        vs.write_text('{ // mine\n}\n', encoding="utf-8")
        sync.write(self.root, self.table, ["copilot-cli"])
        self.assertEqual(vs.read_text(), '{ // mine\n}\n')
        self.assertTrue(any("set \"chat.useClaudeHooks\": true by hand" in p
                            for p in sync.check(self.root, self.table, ["copilot-cli"])))

    def test_a_rule_with_empty_paths_is_one_problem_line(self):
        (self.root / ".claude/rules/bad.md").write_text("---\npaths:\n---\n# Bad\n",
                                                        encoding="utf-8")
        self.assertIn(".github/instructions: .claude/rules/bad.md: paths: is present but"
                      " lists no paths — fix the source or remove copilot-cli",
                      sync.check(self.root, self.table, ["copilot-cli"]))


def git(root, *args):
    """git with no user or system config, so a global excludesFile cannot skew the result."""
    return subprocess.run(["git", *args], cwd=root, capture_output=True, text=True,
                          env={"PATH": os.environ.get("PATH", "/usr/bin:/bin"),
                               "HOME": str(root), "GIT_CONFIG_NOSYSTEM": "1"})


@unittest.skipUnless(shutil.which("git"), "needs git")
class TestGitIgnoredSettings(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = repo(self.tmp.name)
        self.table = sync.load_table()

    def tearDown(self):
        self.tmp.cleanup()

    def test_ignored_vscode_settings_is_not_drift(self):
        git(self.root, "init", "-q")
        (self.root / ".gitignore").write_text(".vscode/\n", encoding="utf-8")
        sync.write(self.root, self.table, ["copilot-cli"])
        (self.root / ".vscode/settings.json").unlink()      # what a fresh clone sees
        self.assertEqual([p for p in sync.check(self.root, self.table, ["copilot-cli"])
                          if "mcp" not in p], [])

    def test_outside_git_a_missing_switch_is_still_drift(self):
        sync.write(self.root, self.table, ["copilot-cli"])
        (self.root / ".vscode/settings.json").unlink()
        self.assertIn('.vscode/settings.json lacks "chat.useClaudeHooks": true',
                      sync.check(self.root, self.table, ["copilot-cli"]))


class TestDeferred(unittest.TestCase):
    """A generated file the operator kept at install time is never overwritten by sync."""

    REL = ".github/copilot-instructions.md"

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = repo(self.tmp.name)
        self.table = sync.load_table()
        (self.root / ".ai-sdlc").mkdir()
        (self.root / ".ai-sdlc/manifest.json").write_text(json.dumps(
            {"harnesses": ["copilot-cli"], "deferred": {self.REL: "0" * 64}}), encoding="utf-8")
        (self.root / ".github").mkdir()
        (self.root / self.REL).write_text("mine\n", encoding="utf-8")

    def tearDown(self):
        self.tmp.cleanup()

    def test_check_says_how_to_hand_the_file_back(self):
        self.assertIn(f"{self.REL} is your file (kit copy in {self.REL}.kit-new) — merge it"
                      f" into its source, delete it, then run {sync.REGENERATE}",
                      sync.check(self.root, self.table, ["copilot-cli"]))

    def test_write_skips_a_kept_file_and_regenerates_a_deleted_one(self):
        errors = []
        self.assertNotIn(self.REL, sync.write(self.root, self.table, ["copilot-cli"], errors))
        self.assertEqual((self.root / self.REL).read_text(), "mine\n")
        self.assertEqual(len(errors), 1)
        (self.root / self.REL).unlink()                      # handed back to the kit
        self.assertIn(self.REL, sync.write(self.root, self.table, ["copilot-cli"], []))


NO_STARTUP = AGENTS.replace("## 0. Startup", "## 9. Startup")


class TestRenderErrors(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = repo(self.tmp.name, NO_STARTUP)
        self.table = sync.load_table()

    def tearDown(self):
        self.tmp.cleanup()

    def test_missing_section_is_one_problem_line(self):
        problems = sync.check(self.root, self.table, ["copilot-cli"])
        self.assertIn(".github/copilot-instructions.md: AGENTS.md has no section(s): 0"
                      " — fix the source or remove copilot-cli", problems)

    def test_write_skips_the_broken_surface_and_writes_the_rest(self):
        errors = []
        written = sync.write(self.root, self.table, ["copilot-cli"], errors)
        self.assertIn(".vscode/settings.json", written)
        self.assertIn(".copilot/mcp-config.json", written)
        self.assertFalse((self.root / ".github/copilot-instructions.md").exists())
        self.assertEqual(len(errors), 1)
        (self.root / ".ai-sdlc").mkdir()
        (self.root / ".ai-sdlc/manifest.json").write_text(
            '{"harnesses": ["copilot-cli"]}', encoding="utf-8")
        with contextlib.redirect_stdout(io.StringIO()), \
             contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(sync.main(["--root", str(self.root), "--write"]), 1)


if __name__ == "__main__":
    unittest.main()
