#!/usr/bin/env python3
"""Unit tests for the Copilot surfaces generated by scripts/harness/sync.py."""
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "harness"))
import sync  # noqa: E402

AGENTS = """# AGENTS.md — `Demo`

Intro.

---

## 0. Startup — user identity and onboarding

1. **If `USER.md` does not exist** → follow [`ONBOARDING.md`](./ONBOARDING.md).

---

## 1. Mission

Not copied.

## 3. Hard constraints (non-negotiable)

- **No secrets in the repo.**

## 4. AI tools & the trust contract

### 4.1 Tools in use

Not copied either.
"""

BRIEF_SPEC = {"kind": "generated", "path": ".github/copilot-instructions.md",
              "format": "copilot-brief", "sections": ["0", "3"]}


def repo(tmp, agents=AGENTS):
    root = Path(tmp)
    (root / "AGENTS.md").write_text(agents, encoding="utf-8")
    return root


class TestBrief(unittest.TestCase):
    def test_inlines_only_the_requested_sections(self):
        with tempfile.TemporaryDirectory() as tmp:
            text = sync.render_copilot_brief(repo(tmp), BRIEF_SPEC)
            self.assertIn("## 0. Startup", text)
            self.assertIn("## 3. Hard constraints", text)
            self.assertNotIn("## 1. Mission", text)
            self.assertNotIn("### 4.1", text)

    def test_marks_itself_generated_and_points_at_agents(self):
        with tempfile.TemporaryDirectory() as tmp:
            text = sync.render_copilot_brief(repo(tmp), BRIEF_SPEC)
            self.assertIn(sync.GENERATED_MARK, text)
            self.assertIn("](../AGENTS.md)", text)

    def test_rewrites_repo_relative_links_for_the_github_folder(self):
        with tempfile.TemporaryDirectory() as tmp:
            text = sync.render_copilot_brief(repo(tmp), BRIEF_SPEC)
            self.assertIn("](../ONBOARDING.md)", text)
            self.assertNotIn("](./ONBOARDING.md)", text)

    def test_drops_section_separators(self):
        with tempfile.TemporaryDirectory() as tmp:
            text = sync.render_copilot_brief(repo(tmp), BRIEF_SPEC)
            self.assertNotIn("\n---\n\n## 3.", text)

    def test_missing_section_is_an_error_not_a_silent_gap(self):
        with tempfile.TemporaryDirectory() as tmp:
            spec = dict(BRIEF_SPEC, sections=["0", "9"])
            with self.assertRaises(ValueError) as ctx:
                sync.render_copilot_brief(repo(tmp), spec)
            self.assertIn("9", str(ctx.exception))


RULES_SPEC = {"kind": "generated", "path": ".github/instructions",
              "format": "copilot-instructions", "from": ".claude/rules"}


def rules(tmp, files):
    root = Path(tmp)
    (root / ".claude/rules").mkdir(parents=True)
    for name, text in files.items():
        (root / ".claude/rules" / name).write_text(text, encoding="utf-8")
    return root


class TestInstructions(unittest.TestCase):
    def test_paths_become_apply_to(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = rules(tmp, {"adr.md": '---\npaths:\n  - "docs/adr/**"\n  - "docs/x/**"\n---\n# ADR\nBody.\n'})
            out = sync.render_copilot_instructions(root, RULES_SPEC)
            text = out[".github/instructions/adr.instructions.md"]
            self.assertTrue(text.startswith("---\napplyTo: 'docs/adr/**,docs/x/**'\n---\n"))
            self.assertIn("# ADR\nBody.", text)
            self.assertIn(sync.GENERATED_MARK, text)

    def test_rule_without_paths_applies_everywhere(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = rules(tmp, {"tokens.md": "# Token economy\nRule.\n"})
            text = sync.render_copilot_instructions(root, RULES_SPEC)[
                ".github/instructions/tokens.instructions.md"]
            self.assertTrue(text.startswith("---\napplyTo: '**'\n---\n"))

    def test_orphans_are_only_our_generated_files(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = rules(tmp, {"a.md": "# A\n"})
            out_dir = root / ".github/instructions"
            out_dir.mkdir(parents=True)
            (out_dir / "gone.instructions.md").write_text(
                f"<!-- {sync.GENERATED_MARK} -->\n", encoding="utf-8")
            (out_dir / "cartograph.instructions.md").write_text("not ours\n", encoding="utf-8")
            wanted = sync.render_copilot_instructions(root, RULES_SPEC)
            self.assertEqual(sync.orphan_instructions(root, RULES_SPEC, wanted),
                             [".github/instructions/gone.instructions.md"])


class TestVscode(unittest.TestCase):
    def test_adds_the_switch_and_keeps_existing_settings(self):
        out = sync.render_vscode_settings('{"editor.tabSize": 2}')
        data = json.loads(out)
        self.assertIs(data["chat.useClaudeHooks"], True)
        self.assertEqual(data["editor.tabSize"], 2)

    def test_operator_false_wins(self):
        out = sync.render_vscode_settings('{"chat.useClaudeHooks": false}')
        self.assertIs(json.loads(out)["chat.useClaudeHooks"], False)

    def test_jsonc_is_left_untouched(self):
        jsonc = '{\n  // my comment\n  "a": 1\n}\n'
        self.assertEqual(sync.render_vscode_settings(jsonc), jsonc)

    def test_state(self):
        self.assertEqual(sync.vscode_hooks_state('{"chat.useClaudeHooks": true}'), "ok")
        self.assertEqual(sync.vscode_hooks_state('{}'), "missing")
        self.assertEqual(sync.vscode_hooks_state('{"chat.useClaudeHooks": false}'), "disabled")
        self.assertEqual(sync.vscode_hooks_state('{ // c\n}'), "unparseable")


class TestCheckWrite(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = repo(self.tmp.name)
        (self.root / ".claude/rules").mkdir(parents=True)
        (self.root / ".claude/rules/adr.md").write_text(
            '---\npaths:\n  - "docs/adr/**"\n---\n# ADR\n', encoding="utf-8")
        self.table = sync.load_table()

    def tearDown(self):
        self.tmp.cleanup()

    def test_fresh_repo_drifts_then_write_fixes_it(self):
        problems = sync.check(self.root, self.table, ["copilot-cli"])
        self.assertTrue(any("copilot-instructions.md" in p for p in problems))
        written = sync.write(self.root, self.table, ["copilot-cli"])
        self.assertIn(".github/copilot-instructions.md", written)
        self.assertIn(".github/instructions/adr.instructions.md", written)
        self.assertIn(".vscode/settings.json", written)
        self.assertEqual([p for p in sync.check(self.root, self.table, ["copilot-cli"])
                          if "mcp" not in p], [])

    def test_editing_agents_md_is_drift(self):
        sync.write(self.root, self.table, ["copilot-cli"])
        agents = self.root / "AGENTS.md"
        agents.write_text(agents.read_text().replace("No secrets", "No secrets, ever"),
                          encoding="utf-8")
        problems = sync.check(self.root, self.table, ["copilot-cli"])
        self.assertIn(".github/copilot-instructions.md differs from its source", problems)

    def test_deleted_rule_leaves_an_orphan_that_write_removes(self):
        sync.write(self.root, self.table, ["copilot-cli"])
        (self.root / ".claude/rules/adr.md").unlink()
        self.assertIn(".github/instructions/adr.instructions.md is an orphan",
                      sync.check(self.root, self.table, ["copilot-cli"]))
        sync.write(self.root, self.table, ["copilot-cli"])
        self.assertFalse((self.root / ".github/instructions/adr.instructions.md").exists())

    def test_unparseable_vscode_settings_is_reported_not_rewritten(self):
        vs = self.root / ".vscode/settings.json"
        vs.parent.mkdir()
        vs.write_text('{ // mine\n}\n', encoding="utf-8")
        sync.write(self.root, self.table, ["copilot-cli"])
        self.assertEqual(vs.read_text(), '{ // mine\n}\n')
        self.assertTrue(any("set \"chat.useClaudeHooks\": true by hand" in p
                            for p in sync.check(self.root, self.table, ["copilot-cli"])))


def git(root, *args):
    """git with no user or system config, so a global excludesFile cannot skew the result."""
    return subprocess.run(["git", *args], cwd=root, capture_output=True, text=True,
                          env={"PATH": os.environ.get("PATH", "/usr/bin:/bin"),
                               "HOME": str(root), "GIT_CONFIG_NOSYSTEM": "1"})


@unittest.skipUnless(shutil.which("git"), "needs git")
class TestGitIgnoredSettings(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = repo(self.tmp.name)
        self.table = sync.load_table()

    def tearDown(self):
        self.tmp.cleanup()

    def test_ignored_vscode_settings_is_not_drift(self):
        git(self.root, "init", "-q")
        (self.root / ".gitignore").write_text(".vscode/\n", encoding="utf-8")
        sync.write(self.root, self.table, ["copilot-cli"])
        (self.root / ".vscode/settings.json").unlink()      # what a fresh clone sees
        self.assertEqual([p for p in sync.check(self.root, self.table, ["copilot-cli"])
                          if "mcp" not in p], [])

    def test_outside_git_a_missing_switch_is_still_drift(self):
        sync.write(self.root, self.table, ["copilot-cli"])
        (self.root / ".vscode/settings.json").unlink()
        self.assertIn('.vscode/settings.json lacks "chat.useClaudeHooks": true',
                      sync.check(self.root, self.table, ["copilot-cli"]))


class TestDeferred(unittest.TestCase):
    """A generated file the operator kept at install time is never overwritten by sync."""

    REL = ".github/copilot-instructions.md"

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = repo(self.tmp.name)
        self.table = sync.load_table()
        (self.root / ".ai-sdlc").mkdir()
        (self.root / ".ai-sdlc/manifest.json").write_text(json.dumps(
            {"harnesses": ["copilot-cli"], "deferred": {self.REL: "0" * 64}}), encoding="utf-8")
        (self.root / ".github").mkdir()
        (self.root / self.REL).write_text("mine\n", encoding="utf-8")

    def tearDown(self):
        self.tmp.cleanup()

    def test_check_says_how_to_hand_the_file_back(self):
        self.assertIn(f"{self.REL} is your file (kit copy in {self.REL}.kit-new) — merge it"
                      f" into its source, delete it, then run {sync.REGENERATE}",
                      sync.check(self.root, self.table, ["copilot-cli"]))

    def test_write_skips_a_kept_file_and_regenerates_a_deleted_one(self):
        errors = []
        self.assertNotIn(self.REL, sync.write(self.root, self.table, ["copilot-cli"], errors))
        self.assertEqual((self.root / self.REL).read_text(), "mine\n")
        self.assertEqual(len(errors), 1)
        (self.root / self.REL).unlink()                      # handed back to the kit
        self.assertIn(self.REL, sync.write(self.root, self.table, ["copilot-cli"], []))


if __name__ == "__main__":
    unittest.main()
